### ISSUE TITLE
TFLite 1.13.1 installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#105]
On a Ubuntu 18.04, I get:
```
$ ck install package:lib-tflite-1.13.1-src-static [--target_os=android23-arm64]
...
downloading https://mirror.bazel.build/github.com/google/farmhash/archive/816a4ae622e964763ca0862d9dbd19324a1eaf45.tar.gz
downloading https://github.com/google/flatbuffers/archive/1f5eae5d6a135ff6811724f6c57f911d1f46bb15.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

This is weird 'cause:
```
$ ck install package:lib-tensorflow-1.13.1-src-static [--target_os=android23-arm64]
```
works just fine.

Any ideas?

**Comment by bellycat77** [comment]
I don't have such problem on the same version of Ubuntu.
Common recommendations:
1. Check free space on filesystem
2. Check if last system updates are installed
3. Try to restart your computer/system
4. Check which `tar` and `gzip` are using. It should look like this:
```
$ which gzip
/bin/gzip
$ gzip --version
gzip 1.6
```
```
$ which tar
/bin/tar
$ tar --version
tar (GNU tar) 1.29
```
5. Try to reinstall the package

**Comment by psyhtest** [comment]
The only difference I see between my Ubuntu 18.04 and 16.04 machines is the version of `tar`: `1.29` vs `1.28`. But `1.29` works for you, right?

**Comment by psyhtest** [comment]
It looks that:
```
$ ck install package:lib-tflite-1.13.1-src-static [--target_os=android23-arm64]
```
now works on my Ubuntu 18.04 machine (after a shutdown).

The only weird thing is that it seems to be using a single thread only?

**Comment by psyhtest** [comment]
OK, I've [enabled](https://github.com/ctuning/ck-tensorflow/commit/a5b9c17195f0f81a5158a1973e423689c973ab03) building TFLite using all CPU cores.
