### ISSUE TITLE
Improve the handling of SqueezeDet

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#11]
Thanks to @fanranGit, CK-TensorFlow now supports the [SqueezeDet artefact](https://github.com/BichenWuUCB/squeezeDet) by @BichenWuUCB et al.

I suggest to make several improvements to this artefact to bring into a more canonical CK form.

1. To allow for other artefacts that use other parts of the [KITTI dataset](http://www.cvlibs.net/datasets/kitti), the object detection evaluation dataset used by SqueezeDet can be called `dataset-kitti-object-image-2` ("left color images of object data set") with the labels called `dataset-kitti-object-label-2`. The images and labels can be related to each other similarly to the [imagenet-val](https://github.com/dividiti/ck-caffe/tree/master/package/imagenet-2012-val) and [imagenet-aux](https://github.com/dividiti/ck-caffe/tree/master/package/imagenet-2012-aux) packages of CK-Caffe. Due to their size, the user should be offered to select the installation path.

1. Splitting of the object data set should be handled similarly to LMDB conversion for CK-Caffe. Specifically, the raw dataset shouldn't be modified, as there may be several different random splittings into the training and validation parts. (Ideally, the splitting process should be governed by a fixed random seed, so that a splitting can be reproduced by giving the same seed.)

1. Currently, `ck run program:squeezedet` prompts for several datasets e.g. `squeezedet-eval-train`. Each such dataset (except `squeezedet-demo`) prompts the user to select one of the classification models (classifiers) e.g. `vgg16`. Note that such prompting is implemented as a bash script, not via CK.
I think it should be cleaner to use CK commands, rather than datasets for choosing between the demo mode, testing on the `val` dataset, testing on the `train` dataset and training proper. The dataset functionality can then be used to select between the classifiers. Furthermore, it should be cleaner to install classifiers separately, not via the [SqueezeDet installation script](https://github.com/ctuning/ck-tensorflow/blob/master/package/tensorflowmodel-squeezedet/install.sh), with packages called something like `squeezedet-classifier-vgg16`.

1. The SqueezeDet artefact should be modified (either via a patch or downloaded from a fork) to update the hardcoded paths to the ones set via CK environment variables (e.g. for KITTI). This is also relevant for the input and output images, checkpoints, temporary directories, etc. (e.g. see [squeezedet_eval_val.sh](https://github.com/ctuning/ck-tensorflow/blob/master/dataset/squeezedet-eval-val/squeezedet_eval_val.sh)).

1. Some performance metrics should be exposed.

Does it make sense? Anything I missed?

**Comment by psyhtest** [comment]
Moreover, the SqueezeDet artefact should be converted to the platform-neutral ("universal") package format, so we can use it on Windows (e.g. on Surface Pro 4).

**Comment by gfursin** [comment]
I see that datasets in ck-tensorflow are not really datasets, but scripts - I feel like that they should become either CMD in program:squeezdet or separate package(s) ...

**Comment by gfursin** [comment]
And one more thing: I don't think OpenCV lib is needed in the dependency of the program:squeezedet since it uses Python cv2 module, right?

**Comment by psyhtest** [comment]
> I don't think OpenCV lib is needed in the dependency of the program:squeezedet since it uses Python cv2 module, right?

I think you are right.

By the way, I documented the dependency on `cv2` [here](https://github.com/ctuning/ck-tensorflow/commit/2acf2a09fe266724cc36308b82aaa8fd443a8b31).

**Comment by psyhtest** [comment]
At the moment, we patch the SqueezeDet demo a lot:
```
Patching source directory ...
/home/anton/CK_REPOS/ck-tensorflow/package/demo-squeezedet-patched/patch.linux/demo.patch
patching file src/demo.py
/home/anton/CK_REPOS/ck-tensorflow/package/demo-squeezedet-patched/patch.linux/python3.patch
patching file src/config/__init__.py
patching file src/config/kitti_model_config.py
patching file src/config/kitti_res50_config.py
patching file src/config/kitti_squeezeDetPlus_config.py
patching file src/config/kitti_squeezeDet_config.py
patching file src/config/kitti_vgg16_config.py
patching file src/dataset/__init__.py
patching file src/dataset/voc_eval.py
patching file src/nets/__init__.py
patching file src/nets/squeezeDet.py
Hunk #1 succeeded at 103 with fuzz 2 (offset 1 line).
/home/anton/CK_REPOS/ck-tensorflow/package/demo-squeezedet-patched/patch.linux/python3extra.patch
patching file src/train.py
```
@Chunosov and I discussed creating our own and more flexible benchmark which would also allow us to measure accuracy in different ways (the native one for KITTI and a somewhat clearer one).

**Comment by psyhtest** [comment]
SqueezeDet has somewhat lost its relevance (although still makes for a great demo), so closing.
