### ISSUE TITLE
SqueezeDet/use_continuous fails with "cannot import name _draw_box"

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#30]
When using TensorFlow (installed from the 1.0.1 or 1.1.0 prebuilt packages):
```
$ ck run program:squeezedet --cmd_key=use_continuous
```
fails with the following message printed to stderr (`tmp/tmp-output2.tmp`):
```
Traceback (most recent call last):
  File "../continuous.py", line 24, in <module>
  from train import _draw_box
ImportError: cannot import name _draw_box
```
At the same time:
```
$ ck run program:squeezedet --cmd_key=default
```
works just fine.

This is on an x86_64 development board with CentOS 7 (Linux kernel 3.10).

**Comment by dsavenko** [comment]
Could you please check is there `_draw_box` function in `CK-TOOLS/demo-squeezedet-patched/squeezeDet/src/train.py`?

**Comment by dsavenko** [comment]
Please, feel free to reopen if the problem still reproduces with TF 1.3 (https://github.com/ctuning/ck-tensorflow/pull/33).
