### ISSUE TITLE
Set up path to bundled protobuf

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#57]
Since TensorFlow depends on `protobuf`, it usually bundles it under `lib/external/protobuf_archive/python`. However, CK-TensorFlow sets `PYTHONPATH` in `env.sh` as follows:
```
PYTHONPATH=/home/anton/CK_TOOLS/lib-tensorflow-src-cpu-xla-1.7-linux-64/lib:${PYTHONPATH}
```
so the bundled `protobuf` is not visible.

This means that if `protobuf` is not installed system-wide (e.g. via `pip`), the following error occurs on importing TensorFlow:
```
$ ck virtual env --tags=lib,tensorflow,vcpu,v1.7

Warning: you are in a new shell with a pre-set CK environment. Enter "exit" to return to the original one!
$ python -c "import tensorflow as tf; print(tf.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anton/CK_TOOLS/lib-tensorflow-src-cpu-xla-1.7-linux-64/lib/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/home/anton/CK_TOOLS/lib-tensorflow-src-cpu-xla-1.7-linux-64/lib/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/anton/CK_TOOLS/lib-tensorflow-src-cpu-xla-1.7-linux-64/lib/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
```

We should extend the environment to set up `PYTHONPATH` e.g. as follows:
```
export PYTHONPATH=/home/anton/CK_TOOLS/lib-tensorflow-src-cuda-xla-1.7-linux-64/lib:/home/anton/CK_TOOLS/lib-tensorflow-src-cuda-xla-1.7-linux-64/lib/external/protobuf_archive/python:${PYTHONPATH}
```

**Comment by psyhtest** [comment]
[Fixed](https://github.com/ctuning/ck-tensorflow/commit/c6fff0c304627b4ca9ed51dd0852bc8e5b888867).

**Comment by psyhtest** [comment]
@gfursin Could you please check this works on Windows when you have time?

**Comment by gfursin** [comment]
@psyhtest - I just checked on Windows, and I see your changes in the new environment. TF classification with such environment continues working (though I have protobuf installed globally), so at least it's not breaking compatibility, so I consider it as fine for now ...
