### ISSUE TITLE
CK-TF support on Tegra TX1 (CPU)

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#6]
The Tegra TX1 CPU is aarch64, while Bazel can currently only be installed from a prebuilt package for x86_64. It seems that Bazel packages exist that are not architecture-specific (e.g. [bazel-0.4.4-dist.zip](https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel-0.4.4-dist.zip)). Can we use them for installing TF on Tegra TX1?

**Comment by gfursin** [comment]
I think I had a package to rebuid bazel, but we need to check that - I didn't look at this for some time now ...

**Comment by psyhtest** [comment]
We already have Bazel packages for up to v0.6.1.

**Comment by psyhtest** [comment]
```
$ ck install package:lib-tensorflow-1.4.0-src-cpu-xla \
--env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=2
...
Installation path: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-xla-1.4-linux-64

Installation time: 13244.4196849 sec.
```
