### ISSUE TITLE
Improving TF installation with versions < 1.4.0 without sudo

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-tensorflow#62]
We unified installation of TF for versions >=1.4.0 which doesn't require SUDO anymore and installs most of Python deps to local user space (CK virtual environments). However, CK installer for TF < 1.4.0 is still old. We should try to update it since there is still legacy code that may require such packages! 

CC @ens-lg4 @psyhtest @gpekhimenko @SerailHydra

**Comment by psyhtest** [comment]
With TensorFlow even a couple of versions back can considered as legacy (e.g. v1.10 now when v1.13 is most recent), it really doesn't make sense to look that far back.
