### ISSUE TITLE
No response while installing bazel on Firefly RK3399

### ISSUE THREAD

**Issue by lucci17** [ctuning/ck-tensorflow#63]
Hi, I try to install tensorflow 1.7.0 on Firefly RK3399 via ck. After I build ck, with commend 'ck install ck-env:package:tool-bazel-0.11.1-linux', terminal can download and fetch bazel. But while compiling, I wait almost 2hrs but there is no response. How can I solve the problem?
I test on Firefly-RK3399-ubuntu16.04-20180416112819 platform.
Thanks !

**Comment by psyhtest** [comment]
Hi @lucci17, two hours sounds excessive! Let's try to debug this together.

When you launch Bazel installation:
```
$ ck install package:tool-bazel-0.11.1-linux
```
you should see something like:
```
Installing to /home/anton/CK_TOOLS/tool-bazel-0.11.1-linux-64

Logging into '/home/anton/CK_TOOLS/tool-bazel-0.11.1-linux-64/ck-install.log' ...

Downloading Bazel from 'https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-dist.zip' ...

Unpacking Bazel to '/home/anton/CK_TOOLS/tool-bazel-0.11.1-linux-64/src' ...

Patching Bazel ...

Compiling Bazel ...
```
If you open another terminal and run `tail -f` on the log, you should see the progress e.g.:
```
$ tail -f /home/anton/CK_TOOLS/tool-bazel-0.11.1-linux-64/ck-install.log
...
[1,619 / 2,152] 3 actions running
    Compiling .../3.4.0/src/google/protobuf/descriptor.pb.cc; 7s local
    JavacBootstrap .../build/buildjar/libskylark-deps.jar [for host]; 7s local
    Compiling src/main/cpp/blaze.cc; 3s local
```

**Comment by lucci17** [comment]
Today, our team has adjusted the code to tf1.1.0 version which is compiled version for RK3399. But the latest tf is essential for the further work. So I will test again on Monday, thanks.

**Comment by lucci17** [comment]
I have installed tf1.4.0, thanks.

**Comment by psyhtest** [comment]
@lucci17 Thanks for confirming!
