### ISSUE TITLE
Patch TensorFlow_CC 1.8.0 similar to TensorFlow 1.8.0 for aarch64 platforms

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#76]
We have a [patch](https://github.com/ctuning/ck-tensorflow/blob/master/package/lib-tensorflow-1.8.0-src-cpu/patch.linux/png.patch) to fix an [issue](https://github.com/tensorflow/tensorflow/issues/18643) with building TensorFlow 1.8.0 on aarch64 platforms. The same should be applied to TensorFlow_CC 1.8.0.

However, simply [placing](https://github.com/ctuning/ck-tensorflow/commit/301046aa98b952a467109b5b60d0282c5363a49d) this patch into `package/lib-tensorflow_cc-shared-1.8.0/patch.linux` doesn't work (which is why I have now [removed](https://github.com/ctuning/ck-tensorflow/commit/562cf0029bc1202827d8a09a4d151a2ca9bbb618) it). 

The existing patches are for TensorFlow_CC itself. However, the new patch should be applied to the TensorFlow sources that get checked out after the initial patches are applied to TensorFlow_CC.

**NB:** While the original issue was fixed in 1.9.0, [another one](https://github.com/tensorflow/tensorflow/issues/18643) was introduced. So we need to think of a generic mechanism for TensorFlow_CC patches.

**Comment by psyhtest** [comment]
Meanwhile, I have manually patched the checked out TensorFlow in the early stages of the build:
```
$ anton@hikey962:~/CK_TOOLS/lib-tensorflow_cc-shared-1.8-gcc-7.2.0-linux-64/obj/tensorflow$ patch -p 1 <  \
/home/anton/CK_REPOS/ck-tensorflow/package/lib-tensorflow-1.8.0-src-cpu/patch.linux/png.patch
```
Will see if it helps in about 10 hours...

**Comment by gfursin** [comment]
Well, when complex patches are needed depending on a version, we have several possible solutions: 

1) we need to somehow prepare them in a pre-processing stage in python. There we can read deps, understand required TF version, and then set environment vars with specific patches. Then install script reads this env and applies patches before building. 

2) provide new mechanism to prepare patches after TF (or any package) is downloaded (to get Git revision for example) and before it's being configured/built. Maybe we can call ck there and pass required info?

I also add @ens-lg4 to CC...

**Comment by psyhtest** [comment]
Just under 5 hours, not bad!
```
anton@hikey962:~/CK_TOOLS$ ck install package:lib-tensorflow_cc-shared-1.8.0 \
--env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=2
...
  Resolving software dependencies ...

*** Dependency 1 = cmake (CMake):

    Resolved. CK environment UID = ceaa21223a3cc6a8 (detected version 3.7.2)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = f122f4b119de8bd8 (detected version 7.2.0)

*** Dependency 3 = bazel (Bazel tool):

    Resolved. CK environment UID = e9bd150b2bb7a468 (detected version 0.13.0)
  -----------------------------------

Environment entry added (5dc2b2453574546b)!

Recording CK configuration to /home/anton/CK_TOOLS/lib-tensorflow_cc-shared-1.8-gcc-7.2.0-linux-64/ck-install.json ...

Installation path: /home/anton/CK_TOOLS/lib-tensorflow_cc-shared-1.8-gcc-7.2.0-linux-64

Installation time: 17893.7106678 sec.
```
But I did have to wait for the TensorFlow_CC installer to clone TensorFlow into `$CK_TOOLS/lib-tensorflow_cc-shared-1.8-gcc-7.2.0-linux-64/obj` and patch it as soon as that was done...

**Comment by Chunosov** [comment]
The patch is automatically applied in this PR https://github.com/ctuning/ck-tensorflow/pull/78.
Here is the essential part: https://github.com/ctuning/ck-tensorflow/pull/78/files#diff-aebaa6ad3fc547f878809f82a61a6a6e
 We have to patch `TensorflowBase.cmake` to force it to patch TF sources. Double shot! :)
