### ISSUE TITLE
image-classification-tf-py imports natively installed TensorFlow module instead of presented in package

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-tensorflow#79]
See `image-classification-tf-py` program, `classify.py`:
```
import tensorflow as tf
```
It is expected that `tensorflow` from selected TF package will be used because we have `PYTHONPATH` assigned in package's env, e.g.:
```
export PYTHONPATH=/home/nchunosov/CK-TOOLS/lib-tensorflow-sycl-opencl-master-compiler.python-3.5.2-lib.opencl-linux-64/lib:/home/nchunosov/CK-TOOLS/lib-tensorflow-sycl-opencl-master-compiler.python-3.5.2-lib.opencl-linux-64/lib/external/protobuf_archive/python:${PYTHONPATH}
```
BUT, as was revealed in https://github.com/ctuning/ck-tensorflow/issues/77, if natively installed TensorFlow library is presented, then **its** module is used instead.

We have to force Python to use package's module.

**Comment by Chunosov** [comment]
The reason is `sys.path` contains standard paths before ones from `PYTHONPATH`. I'm not sure why. We can work around this by manually adding PYTHONPATH's paths into the beginning of `sys.path` before importing TensorFlow. Fixed here: https://github.com/ctuning/ck-tensorflow/pull/82

**Comment by psyhtest** [comment]
Thanks @Chunosov. Is this only applicable to `program:image-classification-tf-py`? What about any of the following:
```
anton@diviniti:~/CK_REPOS/ck-tensorflow/program$ grep "import tensorflow" * -R
image-classification-tf-py/classify.py:import tensorflow as tf
squeezedet/continuous.py:import tensorflow as tf
squeezedet/image_benchmark.py:import tensorflow as tf
tensorflow/classify.py:import tensorflow as tf
tensorflow-classification/classify_image.py:import tensorflow as tf
tensorflow-classification/classify_image.py.new:import tensorflow as tf
tensorflow-freeze/freeze.py:import tensorflow as tf
tensorflow-time/alexnet_benchmark.py.new:import tensorflow as tf
```

**Comment by psyhtest** [comment]
I don't mean that we need to patch all of them, but we use `program:squeezedet` for demos.

**Comment by Chunosov** [comment]
Ideally, all 
```python
import tensorflow as tf
```
should be patched. I'm only not sure if it is the right way to fix this problem...

I mean, It is general problem. We can have different python modules installed in `CK-TOOLS`, not only TensorFlow. And all of them can be potentially ignored by `import` because paths are in wrong order.

**Comment by psyhtest** [comment]
I guess now we just need to check the sort order for all these programs?

**Comment by Chunosov** [comment]
- [x] image-classification-tf-py/classify.py:import tensorflow as tf
- [x] squeezedet/continuous.py:import tensorflow as tf
- [x] squeezedet/image_benchmark.py:import tensorflow as tf
- [x] tensorflow/classify.py:import tensorflow as tf
- [x] tensorflow-classification/classify_image.py:import tensorflow as tf
- [x] tensorflow-classification/classify_image.py.new:import tensorflow as tf
- [x] tensorflow-freeze/freeze.py:import tensorflow as tf
- [x] tensorflow-time/alexnet_benchmark.py.new:import tensorflow as tf

**Comment by Chunosov** [comment]
Checked and fixed a couple of programs (including ` image-classification-tf-py`)
