### ISSUE TITLE
tf lite armeabi version is much slower than the nightly aar 

### ISSUE THREAD

**Issue by zjmirving** [ctuning/ck-tensorflow#90]
At first I was using  'org.tensorflow:tensorflow-lite:0.0.0-nightly'  aar in my own project. My tf lite model costs 900ms. But in my company project, the ndk abiFilters is armeabi.  I changed abiFilters from armeabi-v7a to armeabi. However,  I found the aar not support armeabi.
![image](https://user-images.githubusercontent.com/10142633/48612953-5f35f180-e9c5-11e8-9fde-9faddba7884e.png)
      I compile the armeabi version with the following command, and import so and jar file, but my model costs 4000ms. Is there some wrong with the command ??
bazel build --cxxopt='--std=c++11' //tensorflow/lite/java:tensorflowlite \
--crosstool_top=//external:android/crosstool \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--cpu=armeabi

**Comment by zjmirving** [comment]
wrong project sorry

**Comment by psyhtest** [comment]
Phew, I don't even know what `aar` means :).
