### ISSUE TITLE
There is no object-detection for TFLite

### ISSUE THREAD

**Issue by bellycat77** [ctuning/ck-tensorflow#92]
There is partially raw data after processing image by *.tflite-model like mentioned here: https://github.com/tensorflow/tensorflow/issues/15633#issuecomment-377652630. That data has format `91*1917(scores) + 4*1917(raw coordinates)` float numbers (`class_count*box_count + coordinates_points*box_count`). Scores aren't normalized, but almost each box contains high probability for some class (after normalizing by "box" row). "Raw" coordinates looks inconsistently (`[-0.03030161  1.4208953  -0.01799502  1.3256061 ]
`) after processing by any  of scripts from `https://github.com/tensorflow/models/research/object_detection/box_coders` as mentioned in https://github.com/tf-coreml/tf-coreml/issues/107#issuecomment-359675509

**Comment by psyhtest** [comment]
This is work-in-progress now :)

**Comment by psyhtest** [comment]
See #111.
